CREATE TABLE "qc_inspection_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qc_inspection_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"qc_inspection_id" bigint NOT NULL,
	"receiving_line_id" bigint,
	"item_id" bigint NOT NULL,
	"uom_id" bigint,
	"qty_received" numeric(15, 3) NOT NULL,
	"qty_rejected" numeric(15, 3) DEFAULT '0' NOT NULL,
	"qty_accepted" numeric(15, 3) NOT NULL,
	"batch_number" text,
	"reject_reason" text,
	CONSTRAINT "qc_inspection_lines_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "qc_inspections" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qc_inspections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"document_no" text,
	"series_id" bigint,
	"receiving_id" bigint NOT NULL,
	"purchase_order_id" bigint,
	"supplier_id" bigint,
	"warehouse_id" bigint,
	"inspection_date" date NOT NULL,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"notes" text,
	"qc_notes" text,
	"created_by" bigint,
	"branch_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "qc_inspections_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "qc_inspections_document_no_unique" UNIQUE("document_no")
);
--> statement-breakpoint
ALTER TABLE "qc_inspection_lines" ADD CONSTRAINT "qc_inspection_lines_qc_inspection_id_qc_inspections_id_fk" FOREIGN KEY ("qc_inspection_id") REFERENCES "public"."qc_inspections"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspection_lines" ADD CONSTRAINT "qc_inspection_lines_receiving_line_id_receiving_lines_id_fk" FOREIGN KEY ("receiving_line_id") REFERENCES "public"."receiving_lines"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspection_lines" ADD CONSTRAINT "qc_inspection_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspection_lines" ADD CONSTRAINT "qc_inspection_lines_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspections" ADD CONSTRAINT "qc_inspections_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspections" ADD CONSTRAINT "qc_inspections_receiving_id_receivings_id_fk" FOREIGN KEY ("receiving_id") REFERENCES "public"."receivings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspections" ADD CONSTRAINT "qc_inspections_purchase_order_id_purchase_orders_id_fk" FOREIGN KEY ("purchase_order_id") REFERENCES "public"."purchase_orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspections" ADD CONSTRAINT "qc_inspections_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspections" ADD CONSTRAINT "qc_inspections_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspections" ADD CONSTRAINT "qc_inspections_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspections" ADD CONSTRAINT "qc_inspections_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_qcl_qc" ON "qc_inspection_lines" USING btree ("qc_inspection_id");--> statement-breakpoint
CREATE INDEX "idx_qc_inspections_receiving" ON "qc_inspections" USING btree ("receiving_id");--> statement-breakpoint
CREATE INDEX "idx_qc_inspections_po" ON "qc_inspections" USING btree ("purchase_order_id");--> statement-breakpoint
CREATE INDEX "idx_qc_inspections_status" ON "qc_inspections" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_qc_inspections_document_no" ON "qc_inspections" USING btree ("document_no");