DROP TABLE IF EXISTS "customers" CASCADE;
--> statement-breakpoint
CREATE TABLE "customers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"contact_person" text,
	"phone" text,
	"email" text,
	"address" text,
	"tax_id" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"branch_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "customers_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "customers_code_unique" UNIQUE("code")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "dashboard_widgets" CASCADE;
--> statement-breakpoint
CREATE TABLE "dashboard_widgets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dashboard_widgets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"dashboard_id" bigint NOT NULL,
	"type" text NOT NULL,
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"layout" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "dashboard_widgets_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "dashboards" CASCADE;
--> statement-breakpoint
CREATE TABLE "dashboards" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dashboards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"name" text NOT NULL,
	"owner_id" bigint,
	"branch_id" bigint,
	"workspace_id" bigint,
	"is_global" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "dashboards_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "deliveries" CASCADE;
--> statement-breakpoint
CREATE TABLE "deliveries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deliveries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"document_no" text,
	"series_id" bigint,
	"sales_order_id" bigint,
	"customer_id" bigint,
	"warehouse_id" bigint NOT NULL,
	"delivery_date" date NOT NULL,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"notes" text,
	"created_by" bigint,
	"branch_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "deliveries_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "deliveries_document_no_unique" UNIQUE("document_no")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "delivery_lines" CASCADE;
--> statement-breakpoint
CREATE TABLE "delivery_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "delivery_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"delivery_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"uom_id" bigint NOT NULL,
	"qty" numeric(15, 3) NOT NULL,
	"unit_price" numeric(15, 2),
	"batch_number" text,
	"note" text,
	CONSTRAINT "delivery_lines_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "document_sequences" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "document_sequences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"series_id" bigint NOT NULL,
	"branch_id" bigint,
	"period_key" text NOT NULL,
	"last_number" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "document_series" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "document_series_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"document_type_id" bigint NOT NULL,
	"name" text NOT NULL,
	"prefix" text NOT NULL,
	"format" text DEFAULT '{PREFIX}-{YYMM}-{SEQ:4}' NOT NULL,
	"padding" integer DEFAULT 4 NOT NULL,
	"reset_policy" text DEFAULT 'MONTHLY' NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"branch_specific" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "document_series_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "document_types" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "document_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "document_types_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "document_types_name_unique" UNIQUE("name")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "goods_receipt_lines" CASCADE;
--> statement-breakpoint
CREATE TABLE "goods_receipt_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "goods_receipt_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"goods_receipt_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"uom_id" bigint NOT NULL,
	"qty" numeric(15, 3) NOT NULL,
	"unit_price" numeric(15, 2),
	"batch_number" text,
	"note" text,
	CONSTRAINT "goods_receipt_lines_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "goods_receipts" CASCADE;
--> statement-breakpoint
CREATE TABLE "goods_receipts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "goods_receipts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"document_no" text,
	"series_id" bigint,
	"purchase_order_id" bigint NOT NULL,
	"supplier_id" bigint,
	"warehouse_id" bigint NOT NULL,
	"receipt_date" date NOT NULL,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"notes" text,
	"created_by" bigint,
	"branch_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "goods_receipts_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "goods_receipts_document_no_unique" UNIQUE("document_no")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "opname_count_details" CASCADE;
--> statement-breakpoint
CREATE TABLE "opname_count_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "opname_count_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"count_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"qty" numeric(15, 3) NOT NULL,
	"batch" text,
	"uom_id" bigint,
	"warehouse_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "opname_count_details_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "opname_scan_details" CASCADE;
--> statement-breakpoint
CREATE TABLE "opname_scan_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "opname_scan_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"scan_id" bigint NOT NULL,
	"opname_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"location_id" bigint,
	"item_id" bigint NOT NULL,
	"barcode" text NOT NULL,
	"batch" text,
	"batch_id" bigint,
	"parsed" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"qty_mode" text DEFAULT 'AUTO' NOT NULL,
	"source" text DEFAULT 'SCANNER' NOT NULL,
	"scanned_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "opname_scan_details_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "purchase_order_lines" CASCADE;
--> statement-breakpoint
CREATE TABLE "purchase_order_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_order_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"purchase_order_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"uom_id" bigint NOT NULL,
	"qty" numeric(15, 3) NOT NULL,
	"unit_price" numeric(15, 2),
	"batch_number" text,
	"note" text,
	"delivery_date" date,
	CONSTRAINT "purchase_order_lines_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "purchase_orders" CASCADE;
--> statement-breakpoint
CREATE TABLE "purchase_orders" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"document_no" text,
	"series_id" bigint,
	"supplier_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"order_date" date NOT NULL,
	"expected_date" date,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"notes" text,
	"created_by" bigint,
	"branch_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "purchase_orders_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "purchase_orders_document_no_unique" UNIQUE("document_no")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "sales_order_lines" CASCADE;
--> statement-breakpoint
CREATE TABLE "sales_order_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sales_order_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"sales_order_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"uom_id" bigint NOT NULL,
	"qty" numeric(15, 3) NOT NULL,
	"unit_price" numeric(15, 2),
	"batch_number" text,
	"note" text,
	CONSTRAINT "sales_order_lines_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "sales_orders" CASCADE;
--> statement-breakpoint
CREATE TABLE "sales_orders" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sales_orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"document_no" text,
	"series_id" bigint,
	"customer_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"order_date" date NOT NULL,
	"expected_date" date,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"notes" text,
	"created_by" bigint,
	"branch_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sales_orders_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "sales_orders_document_no_unique" UNIQUE("document_no")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "stock_barcodes" CASCADE;
--> statement-breakpoint
CREATE TABLE "stock_barcodes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_barcodes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"barcode" text NOT NULL,
	"batch_id" bigint,
	"warehouse_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "stock_barcodes_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "stock_barcodes_barcode_unique" UNIQUE("barcode")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "suppliers" CASCADE;
--> statement-breakpoint
CREATE TABLE "suppliers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "suppliers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"contact_person" text,
	"phone" text,
	"email" text,
	"address" text,
	"tax_id" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"branch_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "suppliers_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "suppliers_code_unique" UNIQUE("code")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "workspace_access" CASCADE;
--> statement-breakpoint
CREATE TABLE "workspace_access" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspace_access_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"role_id" bigint NOT NULL,
	"workspace_id" bigint NOT NULL,
	CONSTRAINT "workspace_access_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
DROP TABLE IF EXISTS "workspaces" CASCADE;
--> statement-breakpoint
CREATE TABLE "workspaces" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspaces_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"icon" text DEFAULT 'Layers' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "workspaces_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "workspaces_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE IF EXISTS "opname_entries" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE IF EXISTS "opname_sessions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE IF EXISTS "projects" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE IF EXISTS "scan_records" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE IF EXISTS "scan_sessions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE IF EXISTS "opname_entries" CASCADE;--> statement-breakpoint
DROP TABLE IF EXISTS "opname_sessions" CASCADE;--> statement-breakpoint
DROP TABLE IF EXISTS "projects" CASCADE;--> statement-breakpoint
DROP TABLE IF EXISTS "scan_records" CASCADE;--> statement-breakpoint
DROP TABLE IF EXISTS "scan_sessions" CASCADE;
--> statement-breakpoint
DO $$ DECLARE r RECORD; BEGIN
  FOR r IN SELECT conrelid::regclass::text AS tbl, conname FROM pg_constraint WHERE contype = 'f' AND connamespace = 'public'::regnamespace LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', r.tbl, r.conname);
  END LOOP;
END $$;--> statement-breakpoint
ALTER TABLE "opname_counts" DROP CONSTRAINT IF EXISTS "opname_counts_opname_id_opname_projects_id_fk";
--> statement-breakpoint
ALTER TABLE "opname_counts" DROP CONSTRAINT IF EXISTS "opname_counts_item_id_items_id_fk";
--> statement-breakpoint
ALTER TABLE "opname_counts" DROP CONSTRAINT IF EXISTS "opname_counts_counted_by_users_id_fk";
--> statement-breakpoint
ALTER TABLE "opname_scans" DROP CONSTRAINT IF EXISTS "opname_scans_session_id_opname_sessions_id_fk";
--> statement-breakpoint
ALTER TABLE "opname_scans" DROP CONSTRAINT IF EXISTS "opname_scans_warehouse_id_warehouses_id_fk";
--> statement-breakpoint
ALTER TABLE "opname_scans" DROP CONSTRAINT IF EXISTS "opname_scans_location_id_locations_id_fk";
--> statement-breakpoint
ALTER TABLE "opname_scans" DROP CONSTRAINT IF EXISTS "opname_scans_item_id_items_id_fk";
--> statement-breakpoint
DROP INDEX IF EXISTS "idx_opname_counts_opname";--> statement-breakpoint
DROP INDEX IF EXISTS "idx_opname_scans_session";--> statement-breakpoint
DROP INDEX IF EXISTS "uq_stock_balances_wh_item";--> statement-breakpoint
ALTER TABLE "ai_settings" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "ai_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "barcode_formats" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "barcode_formats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "barcode_formats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "batch_formats" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "batch_formats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "batch_formats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "batches" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "batches" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "batches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "batches" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "batches" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "branch_access" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "branch_access" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "branch_access_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "branch_access" ALTER COLUMN "role_id" SET DATA TYPE bigint USING "role_id"::bigint;--> statement-breakpoint
ALTER TABLE "branch_access" ALTER COLUMN "entity_id" SET DATA TYPE bigint USING "entity_id"::bigint;--> statement-breakpoint
ALTER TABLE "branches" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "branches" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "branches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "item_groups" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "item_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "item_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "items" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "items" ALTER COLUMN "item_group_id" SET DATA TYPE bigint USING "item_group_id"::bigint;--> statement-breakpoint
ALTER TABLE "items" ALTER COLUMN "uom_id" SET DATA TYPE bigint USING "uom_id"::bigint;--> statement-breakpoint
ALTER TABLE "locations" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "locations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "locations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "locations" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "movement_types" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "movement_types" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "movement_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "movement_types" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "opname_counts" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_counts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "opname_counts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "opname_counts" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_counts" ALTER COLUMN "status" SET DEFAULT 'DRAFT';--> statement-breakpoint
ALTER TABLE "opname_projects" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_projects" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "opname_projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "opname_projects" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "opname_scans" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_scans" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "opname_scans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "opname_scans" ALTER COLUMN "opname_id" SET DATA TYPE bigint USING "opname_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_scans" ALTER COLUMN "scanned_by" SET DATA TYPE bigint USING "scanned_by"::bigint;--> statement-breakpoint
ALTER TABLE "opname_warehouses" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_warehouses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "opname_warehouses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "opname_warehouses" ALTER COLUMN "opname_id" SET DATA TYPE bigint USING "opname_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_warehouses" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "refresh_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "refresh_tokens" ALTER COLUMN "user_id" SET DATA TYPE bigint USING "user_id"::bigint;--> statement-breakpoint
ALTER TABLE "role_permissions" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "role_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "role_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "role_permissions" ALTER COLUMN "role_id" SET DATA TYPE bigint USING "role_id"::bigint;--> statement-breakpoint
ALTER TABLE "roles" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stock_balances" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_balances" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_balances_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stock_balances" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_balances" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_batches" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_batches" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_batches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stock_batches" ALTER COLUMN "batch_id" SET DATA TYPE bigint USING "batch_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_batches" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_ledger_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "transaction_id" SET DATA TYPE bigint USING "transaction_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "location_id" SET DATA TYPE bigint USING "location_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "batch_id" SET DATA TYPE bigint USING "batch_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movement_details" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movement_details" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_movement_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stock_movement_details" ALTER COLUMN "movement_id" SET DATA TYPE bigint USING "movement_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movement_details" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movement_details" ALTER COLUMN "from_warehouse_id" SET DATA TYPE bigint USING "from_warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movement_details" ALTER COLUMN "to_warehouse_id" SET DATA TYPE bigint USING "to_warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movement_details" ALTER COLUMN "uom_id" SET DATA TYPE bigint USING "uom_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movement_details" ALTER COLUMN "batch_id" SET DATA TYPE bigint USING "batch_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_movements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "type_id" SET DATA TYPE bigint USING "type_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "uom" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "uom" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "uom_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "uom" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "user_settings" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "user_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "user_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "user_settings" ALTER COLUMN "user_id" SET DATA TYPE bigint USING "user_id"::bigint;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "warehouses" ALTER COLUMN "id" SET DATA TYPE bigint USING "id"::bigint;--> statement-breakpoint
ALTER TABLE "warehouses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "warehouses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "warehouses" ALTER COLUMN "branch_id" SET DATA TYPE bigint USING "branch_id"::bigint;--> statement-breakpoint
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "workspace_id" bigint;--> statement-breakpoint
ALTER TABLE "barcode_formats" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "batch_formats" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "batches" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "branch_access" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "branches" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "item_groups" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "items" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "items" ADD COLUMN IF NOT EXISTS "is_finish_good" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "locations" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "movement_types" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD COLUMN IF NOT EXISTS "document_no" text;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD COLUMN IF NOT EXISTS "series_id" bigint;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD COLUMN IF NOT EXISTS "project_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD COLUMN IF NOT EXISTS "posting_date" date;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD COLUMN IF NOT EXISTS "posting_time" text;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD COLUMN IF NOT EXISTS "cut_off_date" date;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD COLUMN IF NOT EXISTS "cut_off_time" text;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD COLUMN IF NOT EXISTS "notes" text;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD COLUMN IF NOT EXISTS "created_by" bigint;--> statement-breakpoint
ALTER TABLE "opname_projects" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_projects" ADD COLUMN IF NOT EXISTS "document_no" text;--> statement-breakpoint
ALTER TABLE "opname_projects" ADD COLUMN IF NOT EXISTS "series_id" bigint;--> statement-breakpoint
ALTER TABLE "opname_projects" ADD COLUMN IF NOT EXISTS "mode" text DEFAULT 'COMPARE' NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_projects" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_projects" ADD COLUMN IF NOT EXISTS "cut_off_date" date;--> statement-breakpoint
ALTER TABLE "opname_projects" ADD COLUMN IF NOT EXISTS "cut_off_time" text;--> statement-breakpoint
ALTER TABLE "opname_scans" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_scans" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'DRAFT' NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_scans" ADD COLUMN IF NOT EXISTS "started_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_scans" ADD COLUMN IF NOT EXISTS "completed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "opname_scans" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_scans" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "opname_warehouses" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "code" text;--> statement-breakpoint
ALTER TABLE "stock_balances" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_batches" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_ledger" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_movement_details" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD COLUMN IF NOT EXISTS "document_no" text;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD COLUMN IF NOT EXISTS "series_id" bigint;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD COLUMN IF NOT EXISTS "customer_id" bigint;--> statement-breakpoint
ALTER TABLE "uom" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "user_settings" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "role_id" bigint;--> statement-breakpoint
ALTER TABLE "warehouses" ADD COLUMN IF NOT EXISTS "public_id" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "customers" ALTER COLUMN "branch_id" SET DATA TYPE bigint USING "branch_id"::bigint;--> statement-breakpoint
ALTER TABLE "customers" ADD CONSTRAINT "customers_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboard_widgets" ALTER COLUMN "dashboard_id" SET DATA TYPE bigint USING "dashboard_id"::bigint;--> statement-breakpoint
ALTER TABLE "dashboard_widgets" ADD CONSTRAINT "dashboard_widgets_dashboard_id_dashboards_id_fk" FOREIGN KEY ("dashboard_id") REFERENCES "public"."dashboards"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboards" ALTER COLUMN "owner_id" SET DATA TYPE bigint USING "owner_id"::bigint;--> statement-breakpoint
ALTER TABLE "dashboards" ADD CONSTRAINT "dashboards_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboards" ALTER COLUMN "branch_id" SET DATA TYPE bigint USING "branch_id"::bigint;--> statement-breakpoint
ALTER TABLE "dashboards" ADD CONSTRAINT "dashboards_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboards" ALTER COLUMN "workspace_id" SET DATA TYPE bigint USING "workspace_id"::bigint;--> statement-breakpoint
ALTER TABLE "dashboards" ADD CONSTRAINT "dashboards_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deliveries" ALTER COLUMN "series_id" SET DATA TYPE bigint USING "series_id"::bigint;--> statement-breakpoint
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deliveries" ALTER COLUMN "sales_order_id" SET DATA TYPE bigint USING "sales_order_id"::bigint;--> statement-breakpoint
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_sales_order_id_sales_orders_id_fk" FOREIGN KEY ("sales_order_id") REFERENCES "public"."sales_orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deliveries" ALTER COLUMN "customer_id" SET DATA TYPE bigint USING "customer_id"::bigint;--> statement-breakpoint
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deliveries" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deliveries" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deliveries" ALTER COLUMN "branch_id" SET DATA TYPE bigint USING "branch_id"::bigint;--> statement-breakpoint
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "delivery_lines" ALTER COLUMN "delivery_id" SET DATA TYPE bigint USING "delivery_id"::bigint;--> statement-breakpoint
ALTER TABLE "delivery_lines" ADD CONSTRAINT "delivery_lines_delivery_id_deliveries_id_fk" FOREIGN KEY ("delivery_id") REFERENCES "public"."deliveries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "delivery_lines" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "delivery_lines" ADD CONSTRAINT "delivery_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "delivery_lines" ALTER COLUMN "uom_id" SET DATA TYPE bigint USING "uom_id"::bigint;--> statement-breakpoint
ALTER TABLE "delivery_lines" ADD CONSTRAINT "delivery_lines_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_sequences" ALTER COLUMN "series_id" SET DATA TYPE bigint USING "series_id"::bigint;--> statement-breakpoint
ALTER TABLE "document_sequences" ADD CONSTRAINT "document_sequences_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_sequences" ALTER COLUMN "branch_id" SET DATA TYPE bigint USING "branch_id"::bigint;--> statement-breakpoint
ALTER TABLE "document_sequences" ADD CONSTRAINT "document_sequences_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_series" ALTER COLUMN "document_type_id" SET DATA TYPE bigint USING "document_type_id"::bigint;--> statement-breakpoint
ALTER TABLE "document_series" ADD CONSTRAINT "document_series_document_type_id_document_types_id_fk" FOREIGN KEY ("document_type_id") REFERENCES "public"."document_types"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipt_lines" ALTER COLUMN "goods_receipt_id" SET DATA TYPE bigint USING "goods_receipt_id"::bigint;--> statement-breakpoint
ALTER TABLE "goods_receipt_lines" ADD CONSTRAINT "goods_receipt_lines_goods_receipt_id_goods_receipts_id_fk" FOREIGN KEY ("goods_receipt_id") REFERENCES "public"."goods_receipts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipt_lines" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "goods_receipt_lines" ADD CONSTRAINT "goods_receipt_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipt_lines" ALTER COLUMN "uom_id" SET DATA TYPE bigint USING "uom_id"::bigint;--> statement-breakpoint
ALTER TABLE "goods_receipt_lines" ADD CONSTRAINT "goods_receipt_lines_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipts" ALTER COLUMN "series_id" SET DATA TYPE bigint USING "series_id"::bigint;--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD CONSTRAINT "goods_receipts_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipts" ALTER COLUMN "purchase_order_id" SET DATA TYPE bigint USING "purchase_order_id"::bigint;--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD CONSTRAINT "goods_receipts_purchase_order_id_purchase_orders_id_fk" FOREIGN KEY ("purchase_order_id") REFERENCES "public"."purchase_orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipts" ALTER COLUMN "supplier_id" SET DATA TYPE bigint USING "supplier_id"::bigint;--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD CONSTRAINT "goods_receipts_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipts" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD CONSTRAINT "goods_receipts_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipts" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD CONSTRAINT "goods_receipts_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipts" ALTER COLUMN "branch_id" SET DATA TYPE bigint USING "branch_id"::bigint;--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD CONSTRAINT "goods_receipts_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_count_details" ALTER COLUMN "count_id" SET DATA TYPE bigint USING "count_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_count_details" ADD CONSTRAINT "opname_count_details_count_id_opname_counts_id_fk" FOREIGN KEY ("count_id") REFERENCES "public"."opname_counts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_count_details" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_count_details" ADD CONSTRAINT "opname_count_details_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_count_details" ALTER COLUMN "uom_id" SET DATA TYPE bigint USING "uom_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_count_details" ADD CONSTRAINT "opname_count_details_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_count_details" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_count_details" ADD CONSTRAINT "opname_count_details_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ALTER COLUMN "scan_id" SET DATA TYPE bigint USING "scan_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ADD CONSTRAINT "opname_scan_details_scan_id_opname_scans_id_fk" FOREIGN KEY ("scan_id") REFERENCES "public"."opname_scans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ALTER COLUMN "opname_id" SET DATA TYPE bigint USING "opname_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ADD CONSTRAINT "opname_scan_details_opname_id_opname_projects_id_fk" FOREIGN KEY ("opname_id") REFERENCES "public"."opname_projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ADD CONSTRAINT "opname_scan_details_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ALTER COLUMN "location_id" SET DATA TYPE bigint USING "location_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ADD CONSTRAINT "opname_scan_details_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ADD CONSTRAINT "opname_scan_details_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ALTER COLUMN "batch_id" SET DATA TYPE bigint USING "batch_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_scan_details" ADD CONSTRAINT "opname_scan_details_batch_id_batches_id_fk" FOREIGN KEY ("batch_id") REFERENCES "public"."batches"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_order_lines" ALTER COLUMN "purchase_order_id" SET DATA TYPE bigint USING "purchase_order_id"::bigint;--> statement-breakpoint
ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "purchase_order_lines_purchase_order_id_purchase_orders_id_fk" FOREIGN KEY ("purchase_order_id") REFERENCES "public"."purchase_orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_order_lines" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "purchase_order_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_order_lines" ALTER COLUMN "uom_id" SET DATA TYPE bigint USING "uom_id"::bigint;--> statement-breakpoint
ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "purchase_order_lines_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "series_id" SET DATA TYPE bigint USING "series_id"::bigint;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "supplier_id" SET DATA TYPE bigint USING "supplier_id"::bigint;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "branch_id" SET DATA TYPE bigint USING "branch_id"::bigint;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_order_lines" ALTER COLUMN "sales_order_id" SET DATA TYPE bigint USING "sales_order_id"::bigint;--> statement-breakpoint
ALTER TABLE "sales_order_lines" ADD CONSTRAINT "sales_order_lines_sales_order_id_sales_orders_id_fk" FOREIGN KEY ("sales_order_id") REFERENCES "public"."sales_orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_order_lines" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "sales_order_lines" ADD CONSTRAINT "sales_order_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_order_lines" ALTER COLUMN "uom_id" SET DATA TYPE bigint USING "uom_id"::bigint;--> statement-breakpoint
ALTER TABLE "sales_order_lines" ADD CONSTRAINT "sales_order_lines_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_orders" ALTER COLUMN "series_id" SET DATA TYPE bigint USING "series_id"::bigint;--> statement-breakpoint
ALTER TABLE "sales_orders" ADD CONSTRAINT "sales_orders_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_orders" ALTER COLUMN "customer_id" SET DATA TYPE bigint USING "customer_id"::bigint;--> statement-breakpoint
ALTER TABLE "sales_orders" ADD CONSTRAINT "sales_orders_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_orders" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "sales_orders" ADD CONSTRAINT "sales_orders_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_orders" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "sales_orders" ADD CONSTRAINT "sales_orders_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_orders" ALTER COLUMN "branch_id" SET DATA TYPE bigint USING "branch_id"::bigint;--> statement-breakpoint
ALTER TABLE "sales_orders" ADD CONSTRAINT "sales_orders_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_barcodes" ALTER COLUMN "batch_id" SET DATA TYPE bigint USING "batch_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_barcodes" ADD CONSTRAINT "stock_barcodes_batch_id_batches_id_fk" FOREIGN KEY ("batch_id") REFERENCES "public"."batches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_barcodes" ALTER COLUMN "warehouse_id" SET DATA TYPE bigint USING "warehouse_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_barcodes" ADD CONSTRAINT "stock_barcodes_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_barcodes" ALTER COLUMN "item_id" SET DATA TYPE bigint USING "item_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_barcodes" ADD CONSTRAINT "stock_barcodes_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "suppliers" ALTER COLUMN "branch_id" SET DATA TYPE bigint USING "branch_id"::bigint;--> statement-breakpoint
ALTER TABLE "suppliers" ADD CONSTRAINT "suppliers_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_access" ALTER COLUMN "role_id" SET DATA TYPE bigint USING "role_id"::bigint;--> statement-breakpoint
ALTER TABLE "workspace_access" ADD CONSTRAINT "workspace_access_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_access" ALTER COLUMN "workspace_id" SET DATA TYPE bigint USING "workspace_id"::bigint;--> statement-breakpoint
ALTER TABLE "workspace_access" ADD CONSTRAINT "workspace_access_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_deliveries_so" ON "deliveries" USING btree ("sales_order_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_deliveries_wh" ON "deliveries" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_deliveries_customer" ON "deliveries" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_deliveries_status" ON "deliveries" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_deliveries_date" ON "deliveries" USING btree ("delivery_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_deliveries_document_no" ON "deliveries" USING btree ("document_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_dll_delivery" ON "delivery_lines" USING btree ("delivery_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_document_sequences" ON "document_sequences" USING btree ("series_id","branch_id","period_key");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_document_sequences_series" ON "document_sequences" USING btree ("series_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_document_series_type" ON "document_series" USING btree ("document_type_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_document_series_name" ON "document_series" USING btree ("document_type_id","name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_grl_gr" ON "goods_receipt_lines" USING btree ("goods_receipt_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_goods_receipts_po" ON "goods_receipts" USING btree ("purchase_order_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_goods_receipts_wh" ON "goods_receipts" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_goods_receipts_status" ON "goods_receipts" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_goods_receipts_document_no" ON "goods_receipts" USING btree ("document_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_count_details_count" ON "opname_count_details" USING btree ("count_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_count_details_item" ON "opname_count_details" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_count_details_wh" ON "opname_count_details" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_scan_details_scan" ON "opname_scan_details" USING btree ("scan_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_scan_details_opname" ON "opname_scan_details" USING btree ("opname_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_scan_details_wh" ON "opname_scan_details" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_pol_po" ON "purchase_order_lines" USING btree ("purchase_order_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_purchase_orders_supplier" ON "purchase_orders" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_purchase_orders_wh" ON "purchase_orders" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_purchase_orders_status" ON "purchase_orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_purchase_orders_document_no" ON "purchase_orders" USING btree ("document_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_purchase_orders_public_id" ON "purchase_orders" USING btree ("public_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_sol_so" ON "sales_order_lines" USING btree ("sales_order_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_sales_orders_customer" ON "sales_orders" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_sales_orders_wh" ON "sales_orders" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_sales_orders_status" ON "sales_orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_sales_orders_document_no" ON "sales_orders" USING btree ("document_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_barcodes_wh" ON "stock_barcodes" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_barcodes_batch" ON "stock_barcodes" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_barcodes_item" ON "stock_barcodes" USING btree ("item_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_workspace_access" ON "workspace_access" USING btree ("role_id","workspace_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_workspace_access_role" ON "workspace_access" USING btree ("role_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_workspace_access_ws" ON "workspace_access" USING btree ("workspace_id");--> statement-breakpoint
ALTER TABLE "ai_settings" ALTER COLUMN "workspace_id" SET DATA TYPE bigint USING "workspace_id"::bigint;--> statement-breakpoint
ALTER TABLE "ai_settings" ADD CONSTRAINT "ai_settings_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_counts" ALTER COLUMN "series_id" SET DATA TYPE bigint USING "series_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD CONSTRAINT "opname_counts_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_counts" ALTER COLUMN "project_id" SET DATA TYPE bigint USING "project_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD CONSTRAINT "opname_counts_project_id_opname_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."opname_projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_counts" ALTER COLUMN "created_by" SET DATA TYPE bigint USING "created_by"::bigint;--> statement-breakpoint
ALTER TABLE "opname_counts" ADD CONSTRAINT "opname_counts_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opname_projects" ALTER COLUMN "series_id" SET DATA TYPE bigint USING "series_id"::bigint;--> statement-breakpoint
ALTER TABLE "opname_projects" ADD CONSTRAINT "opname_projects_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "series_id" SET DATA TYPE bigint USING "series_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "customer_id" SET DATA TYPE bigint USING "customer_id"::bigint;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "role_id" SET DATA TYPE bigint USING "role_id"::bigint;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_ai_settings_workspace" ON "ai_settings" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_counts_project" ON "opname_counts" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_counts_warehouse" ON "opname_counts" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_counts_created" ON "opname_counts" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_counts_status" ON "opname_counts" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opname_counts_document_no" ON "opname_counts" USING btree ("document_no");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_opname_warehouses_opname_wh" ON "opname_warehouses" USING btree ("opname_id","warehouse_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_stock_balances_wh_item_date" ON "stock_balances" USING btree ("warehouse_id","item_id","balance_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_balances_date" ON "stock_balances" USING btree ("balance_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_ledger_wh_item" ON "stock_ledger" USING btree ("warehouse_id","item_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_ledger_wh_item_date" ON "stock_ledger" USING btree ("warehouse_id","item_id","transaction_date","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_smd_from_wh" ON "stock_movement_details" USING btree ("from_warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_smd_to_wh" ON "stock_movement_details" USING btree ("to_warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_smd_movement_from" ON "stock_movement_details" USING btree ("movement_id","from_warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_smd_movement_to" ON "stock_movement_details" USING btree ("movement_id","to_warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_smd_created" ON "stock_movement_details" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_movements_public_id" ON "stock_movements" USING btree ("public_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_movements_document_no" ON "stock_movements" USING btree ("document_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_movements_created_id" ON "stock_movements" USING btree ("created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_movements_status" ON "stock_movements" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_movements_type" ON "stock_movements" USING btree ("type_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_movements_date" ON "stock_movements" USING btree ("movement_date" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_movements_created" ON "stock_movements" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_stock_movements_type_status" ON "stock_movements" USING btree ("type_id","status");--> statement-breakpoint
ALTER TABLE "opname_counts" DROP COLUMN IF EXISTS "opname_id";--> statement-breakpoint
ALTER TABLE "opname_counts" DROP COLUMN IF EXISTS "item_id";--> statement-breakpoint
ALTER TABLE "opname_counts" DROP COLUMN IF EXISTS "system_qty";--> statement-breakpoint
ALTER TABLE "opname_counts" DROP COLUMN IF EXISTS "counted_qty";--> statement-breakpoint
ALTER TABLE "opname_counts" DROP COLUMN IF EXISTS "difference_qty";--> statement-breakpoint
ALTER TABLE "opname_counts" DROP COLUMN IF EXISTS "counted_at";--> statement-breakpoint
ALTER TABLE "opname_counts" DROP COLUMN IF EXISTS "counted_by";--> statement-breakpoint
ALTER TABLE "opname_scans" DROP COLUMN IF EXISTS "session_id";--> statement-breakpoint
ALTER TABLE "opname_scans" DROP COLUMN IF EXISTS "warehouse_id";--> statement-breakpoint
ALTER TABLE "opname_scans" DROP COLUMN IF EXISTS "location_id";--> statement-breakpoint
ALTER TABLE "opname_scans" DROP COLUMN IF EXISTS "item_id";--> statement-breakpoint
ALTER TABLE "opname_scans" DROP COLUMN IF EXISTS "barcode";--> statement-breakpoint
ALTER TABLE "opname_scans" DROP COLUMN IF EXISTS "scanned_at";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN IF EXISTS "role";--> statement-breakpoint
ALTER TABLE "ai_settings" ADD CONSTRAINT "ai_settings_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "barcode_formats" ADD CONSTRAINT "barcode_formats_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "batch_formats" ADD CONSTRAINT "batch_formats_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "batches" ADD CONSTRAINT "batches_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "branch_access" ADD CONSTRAINT "branch_access_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "branches" ADD CONSTRAINT "branches_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "item_groups" ADD CONSTRAINT "item_groups_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "items" ADD CONSTRAINT "items_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "locations" ADD CONSTRAINT "locations_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "movement_types" ADD CONSTRAINT "movement_types_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "opname_counts" ADD CONSTRAINT "opname_counts_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "opname_counts" ADD CONSTRAINT "opname_counts_document_no_unique" UNIQUE("document_no");--> statement-breakpoint
ALTER TABLE "opname_projects" ADD CONSTRAINT "opname_projects_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "opname_projects" ADD CONSTRAINT "opname_projects_document_no_unique" UNIQUE("document_no");--> statement-breakpoint
ALTER TABLE "opname_scans" ADD CONSTRAINT "opname_scans_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "opname_warehouses" ADD CONSTRAINT "opname_warehouses_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "roles" ADD CONSTRAINT "roles_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "roles" ADD CONSTRAINT "roles_code_unique" UNIQUE("code");--> statement-breakpoint
ALTER TABLE "stock_balances" ADD CONSTRAINT "stock_balances_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "stock_batches" ADD CONSTRAINT "stock_batches_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "stock_ledger" ADD CONSTRAINT "stock_ledger_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "stock_movement_details" ADD CONSTRAINT "stock_movement_details_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_document_no_unique" UNIQUE("document_no");--> statement-breakpoint
ALTER TABLE "uom" ADD CONSTRAINT "uom_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_public_id_unique" UNIQUE("public_id");--> statement-breakpoint
ALTER TABLE "warehouses" ADD CONSTRAINT "warehouses_public_id_unique" UNIQUE("public_id");
--> statement-breakpoint
ALTER TABLE IF EXISTS "item_groups" RENAME CONSTRAINT "categories_pkey" TO "item_groups_pkey";
--> statement-breakpoint
DROP INDEX IF EXISTS "idx_items_is_finish_good";
--> statement-breakpoint
DROP INDEX IF EXISTS "idx_stock_ledger_wh_date";
--> statement-breakpoint
DROP INDEX IF EXISTS "idx_stock_ledger_wh_item_date";
--> statement-breakpoint
DROP INDEX IF EXISTS "idx_stock_movements_customer";
--> statement-breakpoint
CREATE INDEX idx_stock_ledger_wh_item_date ON public.stock_ledger USING btree (warehouse_id, item_id, transaction_date, created_at);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "batches" ADD CONSTRAINT "batches_item_id_items_id_fk" FOREIGN KEY (item_id) REFERENCES items(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "batches" ADD CONSTRAINT "batches_created_by_users_id_fk" FOREIGN KEY (created_by) REFERENCES users(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "branch_access" ADD CONSTRAINT "branch_access_role_id_roles_id_fk" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "items" ADD CONSTRAINT "items_item_group_id_item_groups_id_fk" FOREIGN KEY (item_group_id) REFERENCES item_groups(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "items" ADD CONSTRAINT "items_uom_id_uom_id_fk" FOREIGN KEY (uom_id) REFERENCES uom(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "locations" ADD CONSTRAINT "locations_warehouse_id_warehouses_id_fk" FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "movement_types" ADD CONSTRAINT "movement_types_created_by_users_id_fk" FOREIGN KEY (created_by) REFERENCES users(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "opname_counts" ADD CONSTRAINT "opname_counts_warehouse_id_warehouses_id_fk" FOREIGN KEY (warehouse_id) REFERENCES warehouses(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "opname_projects" ADD CONSTRAINT "opname_projects_created_by_users_id_fk" FOREIGN KEY (created_by) REFERENCES users(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "opname_scans" ADD CONSTRAINT "opname_scans_opname_id_opname_projects_id_fk" FOREIGN KEY (opname_id) REFERENCES opname_projects(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "opname_scans" ADD CONSTRAINT "opname_scans_scanned_by_users_id_fk" FOREIGN KEY (scanned_by) REFERENCES users(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "opname_warehouses" ADD CONSTRAINT "opname_warehouses_opname_id_opname_projects_id_fk" FOREIGN KEY (opname_id) REFERENCES opname_projects(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "opname_warehouses" ADD CONSTRAINT "opname_warehouses_warehouse_id_warehouses_id_fk" FOREIGN KEY (warehouse_id) REFERENCES warehouses(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_users_id_fk" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_roles_id_fk" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_balances" ADD CONSTRAINT "stock_balances_warehouse_id_warehouses_id_fk" FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_balances" ADD CONSTRAINT "stock_balances_item_id_items_id_fk" FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_batches" ADD CONSTRAINT "stock_batches_batch_id_batches_id_fk" FOREIGN KEY (batch_id) REFERENCES batches(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_batches" ADD CONSTRAINT "stock_batches_warehouse_id_warehouses_id_fk" FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_ledger" ADD CONSTRAINT "stock_ledger_item_id_items_id_fk" FOREIGN KEY (item_id) REFERENCES items(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_ledger" ADD CONSTRAINT "stock_ledger_warehouse_id_warehouses_id_fk" FOREIGN KEY (warehouse_id) REFERENCES warehouses(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_ledger" ADD CONSTRAINT "stock_ledger_location_id_locations_id_fk" FOREIGN KEY (location_id) REFERENCES locations(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_ledger" ADD CONSTRAINT "stock_ledger_batch_id_batches_id_fk" FOREIGN KEY (batch_id) REFERENCES batches(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_ledger" ADD CONSTRAINT "stock_ledger_created_by_users_id_fk" FOREIGN KEY (created_by) REFERENCES users(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_movement_details" ADD CONSTRAINT "stock_movement_details_movement_id_stock_movements_id_fk" FOREIGN KEY (movement_id) REFERENCES stock_movements(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_movement_details" ADD CONSTRAINT "stock_movement_details_item_id_items_id_fk" FOREIGN KEY (item_id) REFERENCES items(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_movement_details" ADD CONSTRAINT "stock_movement_details_from_warehouse_id_warehouses_id_fk" FOREIGN KEY (from_warehouse_id) REFERENCES warehouses(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_movement_details" ADD CONSTRAINT "stock_movement_details_to_warehouse_id_warehouses_id_fk" FOREIGN KEY (to_warehouse_id) REFERENCES warehouses(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_movement_details" ADD CONSTRAINT "stock_movement_details_uom_id_uom_id_fk" FOREIGN KEY (uom_id) REFERENCES uom(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_movement_details" ADD CONSTRAINT "stock_movement_details_batch_id_batches_id_fk" FOREIGN KEY (batch_id) REFERENCES batches(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_type_id_movement_types_id_fk" FOREIGN KEY (type_id) REFERENCES movement_types(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_created_by_users_id_fk" FOREIGN KEY (created_by) REFERENCES users(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "uom" ADD CONSTRAINT "uom_created_by_users_id_fk" FOREIGN KEY (created_by) REFERENCES users(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_user_id_users_id_fk" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "warehouses" ADD CONSTRAINT "warehouses_branch_id_branches_id_fk" FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
--> statement-breakpoint
INSERT INTO "workspaces" ("code","name","description","icon","sort_order","public_id") VALUES
  ('stockopname','Stock Opname','Project, Scan & Laporan Opname','ClipboardList',1,'11111111-1111-4111-8111-111111111111'),
  ('warehouse','Warehouse','Stok, Ledger & Master Gudang','Warehouse',2,'22222222-2222-4222-8222-222222222222'),
  ('purchasing','Purchasing','Supplier, PO & Goods Receipt','ShoppingCart',3,'33333333-3333-4333-8333-333333333333'),
  ('marketing','Marketing','Customer & Sales Order','Megaphone',4,'44444444-4444-4444-8444-444444444444')
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "workspace_access" ("role_id","workspace_id","public_id")
SELECT roles.id, workspaces.id, gen_random_uuid() FROM roles CROSS JOIN workspaces
ON CONFLICT DO NOTHING;
