CREATE TABLE "qc_inspection_line_params" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qc_inspection_line_params_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"qc_inspection_line_id" bigint NOT NULL,
	"parameter_id" bigint NOT NULL,
	"qty" numeric(15, 3) NOT NULL,
	"note" text,
	CONSTRAINT "qc_inspection_line_params_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "qc_parameters" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qc_parameters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "qc_parameters_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "qc_parameters_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "qc_inspection_line_params" ADD CONSTRAINT "qc_inspection_line_params_qc_inspection_line_id_qc_inspection_lines_id_fk" FOREIGN KEY ("qc_inspection_line_id") REFERENCES "public"."qc_inspection_lines"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_inspection_line_params" ADD CONSTRAINT "qc_inspection_line_params_parameter_id_qc_parameters_id_fk" FOREIGN KEY ("parameter_id") REFERENCES "public"."qc_parameters"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_qcilp_line" ON "qc_inspection_line_params" USING btree ("qc_inspection_line_id");--> statement-breakpoint
CREATE INDEX "idx_qcilp_param" ON "qc_inspection_line_params" USING btree ("parameter_id");--> statement-breakpoint
CREATE INDEX "idx_qc_params_code" ON "qc_parameters" USING btree ("code");