CREATE TABLE "tax_categories" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tax_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"percentage" numeric(5, 2) NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tax_categories_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "tax_categories_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD COLUMN "tax_category_id" bigint;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_tax_categories_code" ON "tax_categories" USING btree ("code");--> statement-breakpoint
CREATE INDEX "idx_tax_categories_active" ON "tax_categories" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_tax_categories_name" ON "tax_categories" USING btree ("name");--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_tax_category_id_tax_categories_id_fk" FOREIGN KEY ("tax_category_id") REFERENCES "public"."tax_categories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_purchase_orders_tax_category" ON "purchase_orders" USING btree ("tax_category_id");