CREATE TABLE "company_settings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "company_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"company_name" text DEFAULT 'Estoq' NOT NULL,
	"company_code" text DEFAULT 'ESTOQ' NOT NULL,
	"address" text,
	"tax_id" text,
	"country" text DEFAULT 'Indonesia' NOT NULL,
	"base_currency" text DEFAULT 'IDR' NOT NULL,
	"timezone" text DEFAULT 'Asia/Jakarta' NOT NULL,
	"fiscal_year" text DEFAULT 'JANUARY_DECEMBER' NOT NULL,
	"logo" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "company_settings_public_id_unique" UNIQUE("public_id")
);
