CREATE TABLE "price_list_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price_list_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"price_list_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"uom_id" bigint,
	"unit_price" numeric(15, 2) NOT NULL,
	"currency" text DEFAULT 'IDR' NOT NULL,
	"min_qty" numeric(15, 3) DEFAULT '1' NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "price_list_lines_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "price_lists" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price_lists_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"currency" text DEFAULT 'IDR' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"valid_from" date,
	"valid_to" date,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "price_lists_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "price_lists_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "price_list_lines" ADD CONSTRAINT "price_list_lines_price_list_id_price_lists_id_fk" FOREIGN KEY ("price_list_id") REFERENCES "public"."price_lists"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "price_list_lines" ADD CONSTRAINT "price_list_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "price_list_lines" ADD CONSTRAINT "price_list_lines_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "price_lists" ADD CONSTRAINT "price_lists_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_price_list_item" ON "price_list_lines" USING btree ("price_list_id","item_id");--> statement-breakpoint
CREATE INDEX "idx_price_list_lines_price_list" ON "price_list_lines" USING btree ("price_list_id");--> statement-breakpoint
CREATE INDEX "idx_price_list_lines_item" ON "price_list_lines" USING btree ("item_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_price_lists_code" ON "price_lists" USING btree ("code");--> statement-breakpoint
CREATE INDEX "idx_price_lists_active" ON "price_lists" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_price_lists_currency" ON "price_lists" USING btree ("currency");--> statement-breakpoint
ALTER TABLE "items" DROP COLUMN "standard_cost";