CREATE TABLE "user_signatures" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_signatures_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"user_id" bigint NOT NULL,
	"signature_data" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_signatures_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD COLUMN "prepared_signature" text;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD COLUMN "prepared_signed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD COLUMN "prepared_by" bigint;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD COLUMN "approved_signature" text;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD COLUMN "approved_signed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD COLUMN "approved_by" bigint;--> statement-breakpoint
ALTER TABLE "workflow_states" ADD COLUMN "requires_signature" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "user_signatures" ADD CONSTRAINT "user_signatures_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_user_signatures_user" ON "user_signatures" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_user_signatures_user" ON "user_signatures" USING btree ("user_id");--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_prepared_by_users_id_fk" FOREIGN KEY ("prepared_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_approved_by_users_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;