CREATE TABLE "purchase_request_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_request_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"purchase_request_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"uom_id" bigint NOT NULL,
	"qty" numeric(15, 3) NOT NULL,
	"unit_price" numeric(15, 2),
	"discount" numeric(15, 2) DEFAULT '0' NOT NULL,
	"batch_number" text,
	"note" text,
	"delivery_date" date,
	CONSTRAINT "purchase_request_lines_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "purchase_requests" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"document_no" text,
	"series_id" bigint,
	"supplier_id" bigint,
	"warehouse_id" bigint NOT NULL,
	"request_date" date NOT NULL,
	"expected_date" date,
	"urgency" text DEFAULT 'MEDIUM' NOT NULL,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"notes" text,
	"department" text,
	"cost_center" text,
	"currency" text DEFAULT 'IDR' NOT NULL,
	"exchange_rate" numeric(15, 6) DEFAULT '1' NOT NULL,
	"need_approval" boolean DEFAULT false NOT NULL,
	"current_approval_level" integer DEFAULT 0 NOT NULL,
	"approval_workflow_id" bigint,
	"prepared_signature" text,
	"prepared_signed_at" timestamp with time zone,
	"prepared_by" bigint,
	"approved_signature" text,
	"approved_signed_at" timestamp with time zone,
	"approved_by" bigint,
	"global_discount_percent" numeric(5, 2) DEFAULT '0' NOT NULL,
	"additional_charges" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"tax_rate" numeric(5, 2) DEFAULT '0' NOT NULL,
	"tax_category_id" bigint,
	"created_by" bigint,
	"branch_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "purchase_requests_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "purchase_requests_document_no_unique" UNIQUE("document_no")
);
--> statement-breakpoint
ALTER TABLE "purchase_request_lines" ADD CONSTRAINT "purchase_request_lines_purchase_request_id_purchase_requests_id_fk" FOREIGN KEY ("purchase_request_id") REFERENCES "public"."purchase_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_request_lines" ADD CONSTRAINT "purchase_request_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_request_lines" ADD CONSTRAINT "purchase_request_lines_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD CONSTRAINT "purchase_requests_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD CONSTRAINT "purchase_requests_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD CONSTRAINT "purchase_requests_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD CONSTRAINT "purchase_requests_prepared_by_users_id_fk" FOREIGN KEY ("prepared_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD CONSTRAINT "purchase_requests_approved_by_users_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD CONSTRAINT "purchase_requests_tax_category_id_tax_categories_id_fk" FOREIGN KEY ("tax_category_id") REFERENCES "public"."tax_categories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD CONSTRAINT "purchase_requests_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requests" ADD CONSTRAINT "purchase_requests_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_prl_pr" ON "purchase_request_lines" USING btree ("purchase_request_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_requests_supplier" ON "purchase_requests" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_requests_wh" ON "purchase_requests" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_requests_status" ON "purchase_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_purchase_requests_document_no" ON "purchase_requests" USING btree ("document_no");--> statement-breakpoint
CREATE INDEX "idx_purchase_requests_public_id" ON "purchase_requests" USING btree ("public_id");