CREATE TABLE "material_request_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "material_request_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"material_request_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"uom_id" bigint NOT NULL,
	"qty" numeric(15, 3) NOT NULL,
	"note" text,
	"delivery_date" date,
	CONSTRAINT "material_request_lines_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "material_requests" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "material_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"document_no" text,
	"series_id" bigint,
	"warehouse_id" bigint NOT NULL,
	"request_date" date NOT NULL,
	"expected_date" date,
	"urgency" text DEFAULT 'MEDIUM' NOT NULL,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"notes" text,
	"department" text,
	"cost_center" text,
	"need_approval" boolean DEFAULT false NOT NULL,
	"current_approval_level" integer DEFAULT 0 NOT NULL,
	"approval_workflow_id" bigint,
	"prepared_signature" text,
	"prepared_signed_at" timestamp with time zone,
	"prepared_by" bigint,
	"approved_signature" text,
	"approved_signed_at" timestamp with time zone,
	"approved_by" bigint,
	"created_by" bigint,
	"branch_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "material_requests_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "material_requests_document_no_unique" UNIQUE("document_no")
);
--> statement-breakpoint
ALTER TABLE "material_request_lines" ADD CONSTRAINT "material_request_lines_material_request_id_material_requests_id_fk" FOREIGN KEY ("material_request_id") REFERENCES "public"."material_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_request_lines" ADD CONSTRAINT "material_request_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_request_lines" ADD CONSTRAINT "material_request_lines_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_requests" ADD CONSTRAINT "material_requests_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_requests" ADD CONSTRAINT "material_requests_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_requests" ADD CONSTRAINT "material_requests_prepared_by_users_id_fk" FOREIGN KEY ("prepared_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_requests" ADD CONSTRAINT "material_requests_approved_by_users_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_requests" ADD CONSTRAINT "material_requests_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_requests" ADD CONSTRAINT "material_requests_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_mrl_mr" ON "material_request_lines" USING btree ("material_request_id");--> statement-breakpoint
CREATE INDEX "idx_material_requests_wh" ON "material_requests" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX "idx_material_requests_status" ON "material_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_material_requests_document_no" ON "material_requests" USING btree ("document_no");--> statement-breakpoint
CREATE INDEX "idx_material_requests_public_id" ON "material_requests" USING btree ("public_id");