CREATE TABLE "document_activities" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "document_activities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"document_type" text NOT NULL,
	"document_id" bigint NOT NULL,
	"actor_user_id" bigint,
	"actor_role" text,
	"action" text NOT NULL,
	"from_status" text,
	"to_status" text,
	"comment" text,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "document_activities_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "document_activities" ADD CONSTRAINT "document_activities_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_document_activities_doc" ON "document_activities" USING btree ("document_type","document_id");--> statement-breakpoint
CREATE INDEX "idx_document_activities_created" ON "document_activities" USING btree ("created_at");