CREATE TABLE "rfq_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rfq_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"rfq_id" bigint NOT NULL,
	"item_id" bigint NOT NULL,
	"uom_id" bigint NOT NULL,
	"qty" numeric(15, 3) NOT NULL,
	"note" text,
	CONSTRAINT "rfq_lines_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "rfq_suppliers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rfq_suppliers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"rfq_id" bigint NOT NULL,
	"supplier_id" bigint NOT NULL,
	"status" text DEFAULT 'INVITED' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "rfq_suppliers_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "rfqs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rfqs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"document_no" text,
	"series_id" bigint,
	"purchase_request_id" bigint,
	"warehouse_id" bigint NOT NULL,
	"request_date" date NOT NULL,
	"quotation_deadline" date,
	"expected_date" date,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"notes" text,
	"currency" text DEFAULT 'IDR' NOT NULL,
	"awarded_supplier_id" bigint,
	"awarded_at" timestamp with time zone,
	"awarded_by" bigint,
	"created_by" bigint,
	"branch_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "rfqs_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "rfqs_document_no_unique" UNIQUE("document_no")
);
--> statement-breakpoint
CREATE TABLE "supplier_quotation_lines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supplier_quotation_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"quotation_id" bigint NOT NULL,
	"rfq_line_id" bigint,
	"item_id" bigint NOT NULL,
	"uom_id" bigint NOT NULL,
	"qty" numeric(15, 3) NOT NULL,
	"unit_price" numeric(15, 2),
	"discount" numeric(15, 2) DEFAULT '0' NOT NULL,
	"subtotal" numeric(15, 2) DEFAULT '0' NOT NULL,
	"note" text,
	CONSTRAINT "supplier_quotation_lines_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "supplier_quotations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supplier_quotations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"rfq_id" bigint NOT NULL,
	"supplier_id" bigint NOT NULL,
	"quotation_no" text,
	"quotation_date" date NOT NULL,
	"valid_until" date,
	"currency" text DEFAULT 'IDR' NOT NULL,
	"notes" text,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"total_amount" numeric(15, 2) DEFAULT '0' NOT NULL,
	"delivery_lead_time" text,
	"payment_term" text,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "supplier_quotations_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "rfq_lines" ADD CONSTRAINT "rfq_lines_rfq_id_rfqs_id_fk" FOREIGN KEY ("rfq_id") REFERENCES "public"."rfqs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfq_lines" ADD CONSTRAINT "rfq_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfq_lines" ADD CONSTRAINT "rfq_lines_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfq_suppliers" ADD CONSTRAINT "rfq_suppliers_rfq_id_rfqs_id_fk" FOREIGN KEY ("rfq_id") REFERENCES "public"."rfqs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfq_suppliers" ADD CONSTRAINT "rfq_suppliers_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfqs" ADD CONSTRAINT "rfqs_series_id_document_series_id_fk" FOREIGN KEY ("series_id") REFERENCES "public"."document_series"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfqs" ADD CONSTRAINT "rfqs_purchase_request_id_purchase_requests_id_fk" FOREIGN KEY ("purchase_request_id") REFERENCES "public"."purchase_requests"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfqs" ADD CONSTRAINT "rfqs_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfqs" ADD CONSTRAINT "rfqs_awarded_supplier_id_suppliers_id_fk" FOREIGN KEY ("awarded_supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfqs" ADD CONSTRAINT "rfqs_awarded_by_users_id_fk" FOREIGN KEY ("awarded_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfqs" ADD CONSTRAINT "rfqs_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfqs" ADD CONSTRAINT "rfqs_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotation_lines" ADD CONSTRAINT "supplier_quotation_lines_quotation_id_supplier_quotations_id_fk" FOREIGN KEY ("quotation_id") REFERENCES "public"."supplier_quotations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotation_lines" ADD CONSTRAINT "supplier_quotation_lines_rfq_line_id_rfq_lines_id_fk" FOREIGN KEY ("rfq_line_id") REFERENCES "public"."rfq_lines"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotation_lines" ADD CONSTRAINT "supplier_quotation_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotation_lines" ADD CONSTRAINT "supplier_quotation_lines_uom_id_uom_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotations" ADD CONSTRAINT "supplier_quotations_rfq_id_rfqs_id_fk" FOREIGN KEY ("rfq_id") REFERENCES "public"."rfqs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotations" ADD CONSTRAINT "supplier_quotations_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotations" ADD CONSTRAINT "supplier_quotations_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_rfq_lines_rfq" ON "rfq_lines" USING btree ("rfq_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_rfq_supplier" ON "rfq_suppliers" USING btree ("rfq_id","supplier_id");--> statement-breakpoint
CREATE INDEX "idx_rfq_suppliers_rfq" ON "rfq_suppliers" USING btree ("rfq_id");--> statement-breakpoint
CREATE INDEX "idx_rfq_suppliers_supplier" ON "rfq_suppliers" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "idx_rfqs_warehouse" ON "rfqs" USING btree ("warehouse_id");--> statement-breakpoint
CREATE INDEX "idx_rfqs_status" ON "rfqs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_rfqs_document_no" ON "rfqs" USING btree ("document_no");--> statement-breakpoint
CREATE INDEX "idx_rfqs_pr" ON "rfqs" USING btree ("purchase_request_id");--> statement-breakpoint
CREATE INDEX "idx_rfqs_public_id" ON "rfqs" USING btree ("public_id");--> statement-breakpoint
CREATE INDEX "idx_sqlines_quotation" ON "supplier_quotation_lines" USING btree ("quotation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_supplier_quotation_rfq_supplier" ON "supplier_quotations" USING btree ("rfq_id","supplier_id");--> statement-breakpoint
CREATE INDEX "idx_supplier_quotations_rfq" ON "supplier_quotations" USING btree ("rfq_id");--> statement-breakpoint
CREATE INDEX "idx_supplier_quotations_supplier" ON "supplier_quotations" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "idx_supplier_quotations_status" ON "supplier_quotations" USING btree ("status");